# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: example
      # ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  mysql-db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    environment:
      - PMA_HOSTS=mysql-db
      - PMA_PORT=3306
    ports:
      - 8080:80
    restart: always

  aerospikedb:
    image: aerospike:ce-7.0.0.7
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002

  postgresdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data  # Mount a local directory for persistence
    command: redis-server --save 3600 1  # Save snapshot every 3600 seconds if at least 1 key changed

  etcd-00:
    image: quay.io/coreos/etcd:v3.5.0
    hostname: etcd-00
    command:
      - etcd
      - --name=etcd-00
      - --data-dir=data.etcd
      - --advertise-client-urls=http://etcd-00:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd-00:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd-00=http://etcd-00:2380,etcd-01=http://etcd-01:2380,etcd-02=http://etcd-02:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=etcd-cluster-1
    volumes:
      - etcd-00vol:/data.etcd
    networks:
      - etcd
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"
    restart: always

  etcd-01:
    image: quay.io/coreos/etcd:v3.5.0
    hostname: etcd-01
    command:
      - etcd
      - --name=etcd-01
      - --data-dir=data.etcd
      - --advertise-client-urls=http://etcd-01:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd-01:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd-00=http://etcd-00:2380,etcd-01=http://etcd-01:2380,etcd-02=http://etcd-02:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=etcd-cluster-1
    volumes:
      - etcd-01vol:/data.etcd
    networks:
      - etcd
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"
    restart: always

  etcd-02:
    image: quay.io/coreos/etcd:v3.5.0
    hostname: etcd-02
    command:
      - etcd
      - --name=etcd-02
      - --data-dir=data.etcd
      - --advertise-client-urls=http://etcd-02:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd-02:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd-00=http://etcd-00:2380,etcd-01=http://etcd-01:2380,etcd-02=http://etcd-02:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=etcd-cluster-1
    volumes:
      - etcd-02vol:/data.etcd
    networks:
      - etcd
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"
    restart: always

  nginx:
    image: nginx:alpine
    hostname: nginx-etcd
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    networks:
     - etcd
    ports:
      - 2379:2379
    depends_on:
      - etcd-00
      - etcd-01
      - etcd-02
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"
    restart: always

  arangodb:
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: root
    ports:
      - 8529:8529
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps

  orientdb:
    image: broadinstitute/orientdb:latest
    container_name: orientdb_1_nodist
    ports:
      - "2424:2424"
      - "2480:2480"
    environment:
      ORIENTDB_ROOT_PASSWORD: 'rootpwd'
      ORIENTDB_NODE_NAME: 'node1'
    volumes:
      - ~/local/orientdb/node1/databases:/orientdb/databases
      - ~/local/orientdb/node1/backup:/orientdb/backup

volumes:
  arangodb_data_container:
  arangodb_apps_data_container:
  etcd-00vol:
    driver: local
  etcd-01vol:
    driver: local
  etcd-02vol:
    driver: local
  schemas: {}
  rocksdb_data:

networks:
  etcd:
    driver: bridge
